### ISSUE TITLE
make doesn't compile anmy more

### ISSUE THREAD

**Issue by emdio** [koban6/Ray#56]
"make" command just returns an error

$ make
g++ -O3 -Wall -std=c++11  -c src/Command.cpp -o src/Command.o
g++ -O3 -Wall -std=c++11  -c src/DynamicKomi.cpp -o src/DynamicKomi.o
g++ -O3 -Wall -std=c++11  -c src/GoBoard.cpp -o src/GoBoard.o
g++ -O3 -Wall -std=c++11  -c src/Gtp.cpp -o src/Gtp.o
src/Gtp.cpp:29:28: error: ‘GTP_quit’ was not declared in this scope
   { "quit",                GTP_quit                },
                            ^
src/Gtp.cpp:30:28: error: ‘GTP_protocolversion’ was not declared in this scope
   { "protocol_version",    GTP_protocolversion     },
                            ^
src/Gtp.cpp:31:28: error: ‘GTP_name’ was not declared in this scope
   { "name",                GTP_name                },
                            ^
src/Gtp.cpp:32:28: error: ‘GTP_version’ was not declared in this scope
   { "version",             GTP_version             },
                            ^
src/Gtp.cpp:33:28: error: ‘GTP_boardsize’ was not declared in this scope
   { "boardsize",           GTP_boardsize           },
                            ^
src/Gtp.cpp:34:28: error: ‘GTP_clearboard’ was not declared in this scope
   { "clear_board",         GTP_clearboard          },
                            ^
src/Gtp.cpp:35:28: error: ‘GTP_komi’ was not declared in this scope
   { "komi",                GTP_komi                },
                            ^
src/Gtp.cpp:36:28: error: ‘GTP_getkomi’ was not declared in this scope
   { "get_komi",            GTP_getkomi             },
                            ^
src/Gtp.cpp:37:28: error: ‘GTP_play’ was not declared in this scope
   { "play",                GTP_play                },
                            ^
src/Gtp.cpp:38:28: error: ‘GTP_fixed_handicap’ was not declared in this scope
   { "fixed_handicap",      GTP_fixed_handicap      },
                            ^
src/Gtp.cpp:39:28: error: ‘GTP_fixed_handicap’ was not declared in this scope
   { "place_free_handicap", GTP_fixed_handicap      },
                            ^
src/Gtp.cpp:40:28: error: ‘GTP_set_free_handicap’ was not declared in this scope
   { "set_free_handicap",   GTP_set_free_handicap   },
                            ^
src/Gtp.cpp:41:28: error: ‘GTP_genmove’ was not declared in this scope
   { "genmove",             GTP_genmove             }, 
                            ^
src/Gtp.cpp:42:28: error: ‘GTP_timesettings’ was not declared in this scope
   { "time_settings",       GTP_timesettings        },
                            ^
src/Gtp.cpp:43:28: error: ‘GTP_timeleft’ was not declared in this scope
   { "time_left",           GTP_timeleft            },
                            ^
src/Gtp.cpp:44:28: error: ‘GTP_finalscore’ was not declared in this scope
   { "final_score",         GTP_finalscore          },
                            ^
src/Gtp.cpp:45:28: error: ‘GTP_final_status_list’ was not declared in this scope
   { "final_status_list",   GTP_final_status_list   },
                            ^
src/Gtp.cpp:46:28: error: ‘GTP_showboard’ was not declared in this scope
   { "showboard",           GTP_showboard           },
                            ^
src/Gtp.cpp:47:28: error: ‘GTP_listcommands’ was not declared in this scope
   { "list_commands",       GTP_listcommands        },
                            ^
src/Gtp.cpp:48:28: error: ‘GTP_knowncommand’ was not declared in this scope
   { "known_command",       GTP_knowncommand        },
                            ^
src/Gtp.cpp:49:28: error: ‘GTP_kgs_genmove_cleanup’ was not declared in this scope
   { "kgs-genmove_cleanup", GTP_kgs_genmove_cleanup },
                            ^
src/Gtp.cpp:180:1: warning: ‘void GTP_boardsize()’ defined but not used [-Wunused-function]
 GTP_boardsize( void )
 ^
src/Gtp.cpp:218:1: warning: ‘void GTP_clearboard()’ defined but not used [-Wunused-function]
 GTP_clearboard( void )
 ^
src/Gtp.cpp:236:1: warning: ‘void GTP_name()’ defined but not used [-Wunused-function]
 GTP_name( void )
 ^
src/Gtp.cpp:246:1: warning: ‘void GTP_protocolversion()’ defined but not used [-Wunused-function]
 GTP_protocolversion( void )
 ^
src/Gtp.cpp:256:1: warning: ‘void GTP_genmove()’ defined but not used [-Wunused-function]
 GTP_genmove( void )
 ^
src/Gtp.cpp:303:1: warning: ‘void GTP_play()’ defined but not used [-Wunused-function]
 GTP_play( void )
 ^
src/Gtp.cpp:346:1: warning: ‘void GTP_knowncommand()’ defined but not used [-Wunused-function]
 GTP_knowncommand( void )
 ^
src/Gtp.cpp:371:1: warning: ‘void GTP_listcommands()’ defined but not used [-Wunused-function]
 GTP_listcommands( void )
 ^
src/Gtp.cpp:394:1: warning: ‘void GTP_quit()’ defined but not used [-Wunused-function]
 GTP_quit( void )
 ^
src/Gtp.cpp:405:1: warning: ‘void GTP_komi()’ defined but not used [-Wunused-function]
 GTP_komi( void )
 ^
src/Gtp.cpp:425:1: warning: ‘void GTP_getkomi()’ defined but not used [-Wunused-function]
 GTP_getkomi( void )
 ^
src/Gtp.cpp:442:1: warning: ‘void GTP_finalscore()’ defined but not used [-Wunused-function]
 GTP_finalscore( void )
 ^
src/Gtp.cpp:471:1: warning: ‘void GTP_timesettings()’ defined but not used [-Wunused-function]
 GTP_timesettings( void )
 ^
src/Gtp.cpp:497:1: warning: ‘void GTP_timeleft()’ defined but not used [-Wunused-function]
 GTP_timeleft( void )
 ^
src/Gtp.cpp:520:1: warning: ‘void GTP_version()’ defined but not used [-Wunused-function]
 GTP_version( void )
 ^
src/Gtp.cpp:530:1: warning: ‘void GTP_showboard()’ defined but not used [-Wunused-function]
 GTP_showboard( void )
 ^
src/Gtp.cpp:687:1: warning: ‘void GTP_kgs_genmove_cleanup()’ defined but not used [-Wunused-function]
 GTP_kgs_genmove_cleanup( void )
 ^
src/Gtp.cpp:634:1: warning: ‘void GTP_final_status_list()’ defined but not used [-Wunused-function]
 GTP_final_status_list( void )
 ^
src/Gtp.cpp:605:1: warning: ‘void GTP_set_free_handicap()’ defined but not used [-Wunused-function]
 GTP_set_free_handicap( void )
 ^
src/Gtp.cpp:541:1: warning: ‘void GTP_fixed_handicap()’ defined but not used [-Wunused-function]
 GTP_fixed_handicap( void )
 ^
make: *** [src/Gtp.o] Error 1

**Comment by zakki** [comment]
I fixed that. https://github.com/koban6/Ray/pull/55/commits/7058e96ad91762e33e9f7f7cee3e4cdf83a1fa52

**Comment by emdio** [comment]
Not sure what I'm supposed to do with that link. I've replaced in my code the  src/Gtp.cpp and  src/Gtp.h files and "make" still doesn't work, nor does the code in the repository.

BTW, I'm working on linux with gcc 4.8.4

**Comment by emdio** [comment]
After the last additions to the git repo, make still is broken

Ray $ make
g++ -O3 -Wall -std=c++11  -c src/Command.cpp -o src/Command.o
g++ -O3 -Wall -std=c++11  -c src/DynamicKomi.cpp -o src/DynamicKomi.o
g++ -O3 -Wall -std=c++11  -c src/GoBoard.cpp -o src/GoBoard.o
g++ -O3 -Wall -std=c++11  -c src/Gtp.cpp -o src/Gtp.o
src/Gtp.cpp:120:1: error: could not convert ‘{{"quit", GTP_quit}, {"protocol_version", GTP_protocolversion}, {"name", GTP_name}, {"version", GTP_version}, {"boardsize", GTP_boardsize}, {"clear_board", GTP_clearboard}, {"komi", GTP_komi}, {"get_komi", GTP_getkomi}, {"play", GTP_play}, {"fixed_handicap", GTP_fixed_handicap}, {"place_free_handicap", GTP_fixed_handicap}, {"set_free_handicap", GTP_set_free_handicap}, {"genmove", GTP_genmove}, {"time_settings", GTP_timesettings}, {"time_left", GTP_timeleft}, {"final_score", GTP_finalscore}, {"final_status_list", GTP_final_status_list}, {"showboard", GTP_showboard}, {"list_commands", GTP_listcommands}, {"known_command", GTP_knowncommand}, {"kgs-genmove_cleanup", GTP_kgs_genmove_cleanup}}’ from ‘<brace-enclosed initializer list>’ to ‘const std::vector<GTP_command_t>’
 };
 ^
make: *** [src/Gtp.o] Error 1

**Comment by koban6** [comment]
@emdio 
I fixed that bug.
It seems that vector container cannot be initialized by objects.
I tested to build Ray on ubuntu 16.04 and gcc ver 5.4.
Please try to compile again.

**Comment by emdio** [comment]
Tested and now "make" works perfectly. Good job!
